name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Docker App
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo apt update
          sudo apt install -y docker.io git

          # Clone repo
          rm -rf WebApp
          git clone https://github.com/adwognura/WebApp.git
          cd WebApp

          # Build Docker image and run container
          sudo docker build -t webapp .
          sudo docker rm -f webapp-container || true
          sudo docker run -d --name webapp-container -p 8080:8080 webapp
        EOF
#hello world